"""LangGraph nodes and workflow compilation for TianLi Harness."""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Literal, Optional

from langgraph.graph import END, StateGraph

try:  # pragma: no cover - version-dependent import
    from langgraph.checkpoint.sqlite import SqliteSaver
except Exception:  # pragma: no cover - fallback
    SqliteSaver = None

from langgraph.checkpoint.memory import MemorySaver

from tianli_harness.core.interceptor import TianJieInterceptor
from tianli_harness.core.optimizer import TianYanOptimizer
from tianli_harness.core.state import ActionTrace, HarnessConfig, TaskEnvelope, TianLiState
from tianli_harness.dna.fetcher import DNAFetcher
from tianli_harness.skills.claw_proxy import OpenClawSkillManager

logger = logging.getLogger(__name__)


TOOL_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "Read": {"file_path": "README.md"},
    "Write": {"file_path": "notes/output.md", "content": "Generated by TianLi Harness."},
    "Edit": {"file_path": "README.md", "old_text": "", "new_text": "Updated by TianLi Harness."},
    "Grep": {"pattern": "TODO", "path": "."},
    "Glob": {"pattern": "**/*.py", "path": "."},
    "Bash": {"command": "pwd"},
}


class HarnessGraphBuilder:
    """Builder for TianLi Harness LangGraph workflow."""

    def __init__(self, anthropic, skill_manager: OpenClawSkillManager):
        self.anthropic = anthropic
        self.skill_manager = skill_manager

    async def node_fetch_dna(self, state: TianLiState) -> Dict[str, Any]:
        config = state["config"]
        task = state["task"]
        prompt = config.local_hero_prompts.get(config.hero_id, "")

        if not prompt:
            fetcher = DNAFetcher()
            try:
                prompt = await fetcher.fetch(
                    config.hero_id,
                    config.repo_owner,
                    config.repo_name,
                    config.github_token,
                )
            except Exception:
                prompt = f"You are hero '{config.hero_id}'. Stay aligned with the task and explain your reasoning briefly."

        return {
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": task.content},
            ],
            "current_status": "running",
        }

    async def node_agent_reason(self, state: TianLiState) -> Dict[str, Any]:
        messages = state.get("messages", [])
        pending_tool_call = state.get("pending_tool_call")
        if pending_tool_call:
            return {"current_status": state.get("current_status", "running")}

        if not messages:
            return {"current_status": "completed"}

        last_message = messages[-1]
        role = last_message.get("role")
        content = last_message.get("content", "")

        if role == "user" and isinstance(content, str):
            tool_call = self._plan_tool_call(content, state["config"].superpowers)
            if not tool_call:
                summary = f"Hero {state['config'].hero_id} can answer this task without a tool call: {content[:160]}"
                return {
                    "messages": [{"role": "assistant", "content": summary}],
                    "current_status": "completed",
                    "pending_tool_call": None,
                }
            assistant_message = {
                "role": "assistant",
                "content": [
                    {
                        "type": "tool_use",
                        "id": f"tool-{state['task'].task_id}",
                        "name": tool_call["name"],
                        "input": tool_call["input"],
                    }
                ],
            }
            return {
                "messages": [assistant_message],
                "pending_tool_call": tool_call,
                "current_status": "running",
            }

        if role == "user" and isinstance(content, list):
            tool_result = self._extract_tool_result(content)
            result_text = tool_result or "Tool finished."
            summary = (
                f"Hero {state['config'].hero_id} completed the task after one audited tool action. "
                f"Result: {result_text[:200]}"
            )
            return {
                "messages": [{"role": "assistant", "content": summary}],
                "current_status": "completed",
                "pending_tool_call": None,
            }

        return {"current_status": state.get("current_status", "running")}

    async def node_interceptor_audit(self, state: TianLiState) -> Dict[str, Any]:
        config = state["config"]
        traces = state.get("traces", [])
        tool_call = state.get("pending_tool_call")

        if not tool_call:
            return {"current_status": "completed"}

        interceptor = TianJieInterceptor(self.anthropic, config)
        l1_result = interceptor.check_l1(tool_call["name"], tool_call["input"], traces)

        if not l1_result.should_continue:
            return {
                "traces": [self._invalid_trace(state, tool_call, l1_result)],
                "current_status": "early_exit",
                "pending_audit": l1_result.model_dump(),
            }

        if interceptor.should_do_l2_check():
            original_prompt = self._get_original_system_prompt(state.get("messages", []))
            l2_result = await interceptor.check_l2(
                original_prompt,
                state.get("messages", []),
                tool_call["name"],
                tool_call["input"],
            )
            if not l2_result.should_continue:
                return {
                    "traces": [self._invalid_trace(state, tool_call, l2_result)],
                    "current_status": "early_exit",
                    "pending_audit": l2_result.model_dump(),
                }
            return {
                "pending_audit": l2_result.model_dump(),
                "current_status": "running",
            }

        return {
            "pending_audit": l1_result.model_dump(),
            "current_status": "running",
        }

    async def node_execute_claw(self, state: TianLiState) -> Dict[str, Any]:
        traces = state.get("traces", [])
        tool_call = state.get("pending_tool_call")
        pending_audit = state.get("pending_audit") or {}

        if not tool_call:
            return {"current_status": "completed"}

        tool_name = tool_call["name"]
        parameters = tool_call["input"]
        tool_id = tool_call.get("id", f"tool-{len(traces) + 1}")

        result = await self.skill_manager.execute_tool(tool_name, parameters)

        trace = ActionTrace(
            step=len(traces) + 1,
            hero_id=state["config"].hero_id,
            tool_name=tool_name,
            parameters=parameters,
            observation=str(result),
            is_valid=True,
            audit_score=pending_audit.get("score"),
            audit_reason=pending_audit.get("reason", ""),
            audit_stage=pending_audit.get("stage", ""),
        )

        return {
            "traces": [trace],
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "tool_result",
                            "tool_use_id": tool_id,
                            "content": str(result),
                        }
                    ],
                }
            ],
            "pending_tool_call": None,
            "pending_audit": None,
            "current_status": "running",
        }

    async def node_optimizer(self, state: TianLiState) -> Dict[str, Any]:
        optimizer = TianYanOptimizer(self.anthropic, state["config"])
        patch = await optimizer.generate_patch(state.get("messages", []), state.get("traces", []))
        return {
            "evolution_patch": patch,
            "pending_tool_call": None,
            "pending_audit": None,
        }

    def _plan_tool_call(self, content: str, allowed_tools: List[str]) -> Optional[Dict[str, Any]]:
        lowered = content.lower()
        chosen_tool = None

        if any(keyword in lowered for keyword in ("read", "查看", "inspect", "analyze", "读取")) and "Read" in allowed_tools:
            chosen_tool = "Read"
        elif any(keyword in lowered for keyword in ("grep", "search", "find", "查找")) and "Grep" in allowed_tools:
            chosen_tool = "Grep"
        elif any(keyword in lowered for keyword in ("glob", "files", "目录")) and "Glob" in allowed_tools:
            chosen_tool = "Glob"
        elif any(keyword in lowered for keyword in ("write", "create", "生成", "实现")) and "Write" in allowed_tools:
            chosen_tool = "Write"
        elif any(keyword in lowered for keyword in ("edit", "modify", "update", "改")) and "Edit" in allowed_tools:
            chosen_tool = "Edit"
        elif any(keyword in lowered for keyword in ("bash", "shell", "command", "命令")) and "Bash" in allowed_tools:
            chosen_tool = "Bash"
        elif allowed_tools:
            chosen_tool = allowed_tools[0]

        if not chosen_tool:
            return None

        tool_input = dict(TOOL_TEMPLATES.get(chosen_tool, {}))
        hinted_path = self._extract_path_hint(content)
        if hinted_path and chosen_tool in {"Read", "Write", "Edit"}:
            tool_input["file_path"] = hinted_path
        if chosen_tool == "Write":
            tool_input["content"] = f"Task output for: {content}"
        if chosen_tool == "Bash":
            tool_input["command"] = "pwd"

        return {
            "name": chosen_tool,
            "input": tool_input,
            "id": f"tool-{re.sub(r'[^a-z0-9]+', '-', chosen_tool.lower())}",
        }

    def _extract_path_hint(self, content: str) -> Optional[str]:
        match = re.search(r"([A-Za-z0-9_./-]+\.[A-Za-z0-9]+)", content)
        return match.group(1) if match else None

    def _extract_tool_result(self, blocks: List[dict]) -> str:
        for block in blocks:
            if isinstance(block, dict) and block.get("type") == "tool_result":
                return str(block.get("content", ""))
        return ""

    def _get_original_system_prompt(self, messages: List[dict]) -> str:
        for message in messages:
            if message.get("role") == "system":
                return str(message.get("content", ""))
        return ""

    def _invalid_trace(self, state: TianLiState, tool_call: Dict[str, Any], audit_result) -> ActionTrace:
        return ActionTrace(
            step=len(state.get("traces", [])) + 1,
            hero_id=state["config"].hero_id,
            tool_name=tool_call["name"],
            parameters=tool_call["input"],
            observation=f"Blocked before execution: {audit_result.reason}",
            is_valid=False,
            audit_score=audit_result.score,
            audit_reason=audit_result.reason,
            audit_stage=audit_result.stage,
        )


def route_after_reason(state: TianLiState) -> Literal["to_audit", "to_end"]:
    if state.get("pending_tool_call"):
        return "to_audit"
    return "to_end"


def route_after_audit(state: TianLiState) -> Literal["execute", "trigger_early_exit"]:
    if state.get("current_status") == "early_exit":
        return "trigger_early_exit"
    return "execute"


def _build_checkpointer(config: HarnessConfig):
    if SqliteSaver is not None:
        try:
            return SqliteSaver.from_conn_string(config.checkpoint_path)
        except Exception:  # pragma: no cover - filesystem fallback
            logger.warning("Falling back to in-memory checkpoints", exc_info=True)
    return MemorySaver()


def build_harness_graph(config: HarnessConfig, anthropic, skill_manager: OpenClawSkillManager):
    builder = HarnessGraphBuilder(anthropic, skill_manager)
    workflow = StateGraph(TianLiState)

    workflow.add_node("fetch_dna", builder.node_fetch_dna)
    workflow.add_node("reason", builder.node_agent_reason)
    workflow.add_node("audit", builder.node_interceptor_audit)
    workflow.add_node("claw_exec", builder.node_execute_claw)
    workflow.add_node("optimizer", builder.node_optimizer)

    workflow.set_entry_point("fetch_dna")
    workflow.add_edge("fetch_dna", "reason")
    workflow.add_conditional_edges("reason", route_after_reason, {"to_audit": "audit", "to_end": END})
    workflow.add_conditional_edges(
        "audit",
        route_after_audit,
        {"execute": "claw_exec", "trigger_early_exit": "optimizer"},
    )
    workflow.add_edge("claw_exec", "reason")
    workflow.add_edge("optimizer", END)

    return workflow.compile(checkpointer=_build_checkpointer(config))


class HarnessEngine:
    """Main entry point for TianLi Harness engine."""

    def __init__(self, config: HarnessConfig, anthropic, openclaw_executor):
        self.config = config
        self.anthropic = anthropic
        self.skill_manager = OpenClawSkillManager(openclaw_executor)
        self.app = build_harness_graph(config, anthropic, self.skill_manager)

    async def run(self, thread_id: str, user_input: str):
        initial_state: TianLiState = {
            "config": self.config,
            "task": TaskEnvelope(
                task_id=thread_id,
                content=user_input,
                max_fanout=self.config.max_fanout,
                dispatch_mode=self.config.dispatch_mode,
            ),
            "messages": [],
            "traces": [],
            "task_flow": [],
            "current_status": "starting",
            "evolution_patch": "",
            "pending_tool_call": None,
            "pending_audit": None,
            "dispatch_decision": None,
        }
        return await self.app.ainvoke(initial_state, config={"configurable": {"thread_id": thread_id}})
