/** @type {import('tailwindcss').Config} */
export default {{
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {{
    extend: {{
      colors: {{
        primary: {{
          50: '{DESIGN_SYSTEM["colors"]["primary"]["50"]}',
          100: '{DESIGN_SYSTEM["colors"]["primary"]["100"]}',
          200: '{DESIGN_SYSTEM["colors"]["primary"]["200"]}',
          300: '{DESIGN_SYSTEM["colors"]["primary"]["300"]}',
          400: '{DESIGN_SYSTEM["colors"]["primary"]["400"]}',
          500: '{DESIGN_SYSTEM["colors"]["primary"]["500"]}',
          600: '{DESIGN_SYSTEM["colors"]["primary"]["600"]}',
          700: '{DESIGN_SYSTEM["colors"]["primary"]["700"]}',
          800: '{DESIGN_SYSTEM["colors"]["primary"]["800"]}',
          900: '{DESIGN_SYSTEM["colors"]["primary"]["900"]}',
        }},
        secondary: {{
          50: '{DESIGN_SYSTEM["colors"]["secondary"]["50"]}',
          100: '{DESIGN_SYSTEM["colors"]["secondary"]["100"]}',
          200: '{DESIGN_SYSTEM["colors"]["secondary"]["200"]}',
          300: '{DESIGN_SYSTEM["colors"]["secondary"]["300"]}',
          400: '{DESIGN_SYSTEM["colors"]["secondary"]["400"]}',
          500: '{DESIGN_SYSTEM["colors"]["secondary"]["500"]}',
          600: '{DESIGN_SYSTEM["colors"]["secondary"]["600"]}',
          700: '{DESIGN_SYSTEM["colors"]["secondary"]["700"]}',
          800: '{DESIGN_SYSTEM["colors"]["secondary"]["800"]}',
          900: '{DESIGN_SYSTEM["colors"]["secondary"]["900"]}',
        }},
        success: {{
          50: '{DESIGN_SYSTEM["colors"]["success"]["50"]}',
          100: '{DESIGN_SYSTEM["colors"]["success"]["100"]}',
          200: '{DESIGN_SYSTEM["colors"]["success"]["200"]}',
          300: '{DESIGN_SYSTEM["colors"]["success"]["300"]}',
          400: '{DESIGN_SYSTEM["colors"]["success"]["400"]}',
          500: '{DESIGN_SYSTEM["colors"]["success"]["500"]}',
          600: '{DESIGN_SYSTEM["colors"]["success"]["600"]}',
          700: '{DESIGN_SYSTEM["colors"]["success"]["700"]}',
          800: '{DESIGN_SYSTEM["colors"]["success"]["800"]}',
          900: '{DESIGN_SYSTEM["colors"]["success"]["900"]}',
        }},
        warning: {{
          50: '{DESIGN_SYSTEM["colors"]["warning"]["50"]}',
          100: '{DESIGN_SYSTEM["colors"]["warning"]["100"]}',
          200: '{DESIGN_SYSTEM["colors"]["warning"]["200"]}',
          300: '{DESIGN_SYSTEM["colors"]["warning"]["300"]}',
          400: '{DESIGN_SYSTEM["colors"]["warning"]["400"]}',
          500: '{DESIGN_SYSTEM["colors"]["warning"]["500"]}',
          600: '{DESIGN_SYSTEM["colors"]["warning"]["600"]}',
          700: '{DESIGN_SYSTEM["colors"]["warning"]["700"]}',
          800: '{DESIGN_SYSTEM["colors"]["warning"]["800"]}',
          900: '{DESIGN_SYSTEM["colors"]["warning"]["900"]}',
        }},
      }},
      fontFamily: {{
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }},
      fontSize: {{
        xs: '{DESIGN_SYSTEM["typography"]["scale"]["xs"]}',
        sm: '{DESIGN_SYSTEM["typography"]["scale"]["sm"]}',
        base: '{DESIGN_SYSTEM["typography"]["scale"]["base"]}',
        lg: '{DESIGN_SYSTEM["typography"]["scale"]["lg"]}',
        xl: '{DESIGN_SYSTEM["typography"]["scale"]["xl"]}',
        '2xl': '{DESIGN_SYSTEM["typography"]["scale"]["2xl"]}',
        '3xl': '{DESIGN_SYSTEM["typography"]["scale"]["3xl"]}',
        '4xl': '{DESIGN_SYSTEM["typography"]["scale"]["4xl"]}',
        '5xl': '{DESIGN_SYSTEM["typography"]["scale"]["5xl"]}',
      }},
      spacing: {{
        ...{DESIGN_SYSTEM["spacing"]["scale"]},
      }},
      boxShadow: {{
        sm: '{DESIGN_SYSTEM["shadows"]["sm"]}',
        DEFAULT: '{DESIGN_SYSTEM["shadows"]["base"]}',
        md: '{DESIGN_SYSTEM["shadows"]["md"]}',
        lg: '{DESIGN_SYSTEM["shadows"]["lg"]}',
        xl: '{DESIGN_SYSTEM["shadows"]["xl"]}',
        '2xl': '{DESIGN_SYSTEM["shadows"]["2xl"]}',
        inner: '{DESIGN_SYSTEM["shadows"]["inner"]}',
      }},
      borderRadius: {{
        none: '{DESIGN_SYSTEM["radius"]["none"]}',
        sm: '{DESIGN_SYSTEM["radius"]["sm"]}',
        DEFAULT: '{DESIGN_SYSTEM["radius"]["base"]}',
        md: '{DESIGN_SYSTEM["radius"]["md"]}',
        lg: '{DESIGN_SYSTEM["radius"]["lg"]}',
        xl: '{DESIGN_SYSTEM["radius"]["xl"]}',
        '2xl': '{DESIGN_SYSTEM["radius"]["2xl"]}',
        full: '{DESIGN_SYSTEM["radius"]["full"]}',
      }},
      transitionDuration: {{
        fast: '{DESIGN_SYSTEM["transitions"]["duration"]["fast"]}',
        DEFAULT: '{DESIGN_SYSTEM["transitions"]["duration"]["normal"]}',
        slow: '{DESIGN_SYSTEM["transitions"]["duration"]["slow"]}',
      }},
    }},
  }},
  plugins: [],
}}
